<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Edda.Avalonia</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edda.Core\Edda.Core.csproj" />
    <ProjectReference Include="..\Edda.App\Edda.App.csproj" />
  </ItemGroup>
</Project>
