<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>Edda</RootNamespace>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Edda.Core\Edda.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.1.0" />
    <PackageReference Include="NAudio.Vorbis" Version="1.5.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.17.1" />
    <PackageReference Include="RagnaRuneString" Version="1.0.2" />
    <PackageReference Include="SoundTouch.Net.NAudioSupport.Core" Version="2.3.2" />
    <PackageReference Include="Syncfusion.PMML.Net.Core" Version="20.4.0.43" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Edda.Core\Resources\Edda-MLDP_Nytilde.onnx" Link="Resources\Edda-MLDP_Nytilde.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Edda.Core\Resources\Edda-MLDP_Nytilde_Fallback.onnx" Link="Resources\Edda-MLDP_Nytilde_Fallback.onnx">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="..\Edda.Core\Resources\Edda-MLDP_PKBeam.pmml" Link="Resources\Edda-MLDP_PKBeam.pmml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
